/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javar;

import com.toedter.calendar.IDateEvaluator;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Josep
 */
public class JRCalendarTableView extends javax.swing.JPanel {

    public static final byte TABLEVIEW = 0;
    public static final byte COMPOUNDVIEW = 1;
    protected byte view = 1;
    protected DefaultTableModel modelTable1;
    
    /**
     * Creates new form JRCalendarTableView
     */
    public JRCalendarTableView() {
        initComponents();
        setupView();
        
        this.jRMultiMonthDayChooser1.addPropertyChangeListener(new PropertyChangeListener() {

            @Override
            public void propertyChange(PropertyChangeEvent evt) {
               JRCalendarTableView.this.firePropertyChange("day", evt.getOldValue(), evt.getNewValue());
               fillTable();
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jRMultiMonthDayChooser1 = new javar.JRMultiMonthDayChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javar/icons/table.gif"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("javar/javarbundle"); // NOI18N
        jToggleButton1.setToolTipText(bundle.getString("switchViews")); // NOI18N
        jToggleButton1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/javar/icons/table.gif"))); // NOI18N
        jToggleButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/javar/icons/table2.gif"))); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jRMultiMonthDayChooser1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        modelTable1 = new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {}
        );
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(modelTable1);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 1, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jRMultiMonthDayChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(3, 3, 3)
                .addComponent(jRMultiMonthDayChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        byte oldView = view;
        view = jToggleButton1.isSelected()?COMPOUNDVIEW:TABLEVIEW;
        this.firePropertyChange("view", oldView, view);
        fillTable();
        setupView();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javar.JRMultiMonthDayChooser jRMultiMonthDayChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

    public byte getView() {
        return view;
    }

    public void setView(byte view) {
        this.view = view;        
        setupView();
    }
    
    public void setDateEvaluator(IDateEvaluator iDateEvaluator)
    {
        
    }
    
     public void addDateEvaluator(IDateEvaluator iDateEvaluator) {
        this.getjRMultiMonthDayChooser1().addDateEvaluator(iDateEvaluator);
    }

    private void setupView() {
        this.jToggleButton1.setSelected(view==COMPOUNDVIEW);
        this.getjRMultiMonthDayChooser1().setVisible(view==COMPOUNDVIEW);
    }

    public DefaultTableModel getModelTable1() {
        return modelTable1;
    }

    public void setModelTable1(DefaultTableModel modelTable1) {
        this.modelTable1 = modelTable1;
        jTable1.setModel(modelTable1);
        jTable1.revalidate();
        jTable1.repaint();
    }

    public void clearTable() {
        while(jTable1.getRowCount()>0)
        {
            modelTable1.removeRow(0);
        }
    }
    
    public JRMultiMonthDayChooser getMultiMonthCalendar()
    {
        return getjRMultiMonthDayChooser1();
    }

  
    public void registerType(String typeName, java.awt.Color typeColor)
    {
        JLabel jLabelType = new JLabel("\u25A0 "); 
        jLabelType.setForeground(typeColor);
        jPanel1.add(jLabelType);
        JLabel jLabelType2 = new JLabel(typeName+" "); 
        jPanel1.add(jLabelType2);
    }

    public javar.JRMultiMonthDayChooser getjRMultiMonthDayChooser1() {
        return jRMultiMonthDayChooser1;
    }
    
    
    //Override this method with your desired code
    public void fillTable()
    {
        
    }
}
