/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * XmlTextField.java
 *
 * Created on 01-abr-2012, 8:55:27
 */
package javar;

import java.awt.Color;
import java.awt.Point;
import java.util.HashMap;
import javax.swing.JRadioButton;
import javax.swing.SwingUtilities;
import org.iesapp.framework.util.CoreCfg;

/**
 *
 * @author Josep
 */
public class JRPeriodDateChooser extends javax.swing.JPanel implements JRComponent {
    private String id="";
    private boolean required = false;
    private boolean selectable = false;
    private String selectionFieldName;
    private boolean addtomap;
    private String initialValue;
    private boolean initialSelection;
    private CoreCfg coreCfg;
    /** Creates new form XmlTextField */
    public JRPeriodDateChooser() {

        initComponents();
        jRadioButton1.setVisible(selectable);
        jTextField1.setEditable(false);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setOpaque(false);

        jLabel1.setText("jLabel1");
        jLabel1.setName("jLabel1"); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 14));

        jTextField1.setText("jTextField1");
        jTextField1.setName("jTextField1"); // NOI18N
        jTextField1.setPreferredSize(new java.awt.Dimension(200, 20));

        jRadioButton1.setName("jRadioButton1"); // NOI18N
        jRadioButton1.setOpaque(false);
        jRadioButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton1StateChanged(evt);
            }
        });

        jButton1.setText("···");
        jButton1.setToolTipText("Selecciona periodes");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(1, 1, 1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton1StateChanged
        jTextField1.setVisible(jRadioButton1.isSelected());
    }//GEN-LAST:event_jRadioButton1StateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JRPeriodSelect ps = new JRPeriodSelect(javar.JRDialog.getActiveFrame(), true, coreCfg);
        ps.setPeriods(getValue());
        Point pt = new Point(jTextField1.getLocation()); 
        SwingUtilities.convertPointToScreen(pt, jTextField1);
        ps.setLocation(pt.x-ps.getWidth()/2,pt.y+jTextField1.getHeight());
        
        //ps.setLocation(0,jTextField1.getHeight());
        ps.setVisible(true);
        if(ps.accept)
        {
            setValue(ps.getAllPeriods());
        }
        else if(ps.esborra)
        {
            setValue("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    public void setValue(String value) {
        initialValue = value;
        jTextField1.setText(value);
    }

    public String getValue() {
        return jTextField1.getText();
    }

    public boolean check() {
        boolean check = true;        
        if (required) {
            check = !getValue().trim().isEmpty();
        }
         
        if(!check)
        {
            jLabel1.setBackground(Color.red);
            jLabel1.setOpaque(true);
        }
        else
        {
            jLabel1.setOpaque(false);
        }
        jLabel1.repaint();
        return check;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id=id;
    }

    public void setEnable(boolean enabled) {
        jTextField1.setEnabled(enabled);
        jButton1.setEnabled(enabled);
    }

    public void focus() {
        jTextField1.requestFocusInWindow();
    }

    public void setRequired(boolean required) {
        this.required=required;
    }

    public boolean isRequired() {
       return this.required;
    }

    public void setLabel(String label) {
        this.jLabel1.setText(label);
    }

    public void setSelectable(boolean selectable, String selectionFieldName) {
        this.selectable = selectable;
        this.selectionFieldName = selectionFieldName;
        jRadioButton1.setVisible(selectable);
        if(selectable)
        {
            jTextField1.setVisible(jRadioButton1.isSelected());
        }
    }

    public boolean isSelectable() {
       return selectable;
    }

    public JRadioButton getRadioButton() {
        return jRadioButton1;
    }

    public boolean isSelected() {
        return jRadioButton1.isSelected();
    }

    public String getSelectionFieldName() {
        return selectionFieldName;
    }

    public void setSelectionFieldName(String name) {
        this.selectionFieldName = name;
    }
    
    public void setSelected(boolean selected) {
        initialSelection = selected;
        jRadioButton1.setSelected(selected);
        jTextField1.setVisible(selected);
    }

    public void setIniParams(HashMap<String,Object> params) {
        //
    }

    public boolean isAddToMap() {
        return addtomap;
    }

    public void setAddToMap(boolean settomap) {
        addtomap = settomap;
    }

    public boolean hasChanged() {
        return (!(initialValue.equals(this.getValue())) || (initialSelection!=this.isSelected()));
    }
    
     @Override
    public void setCoreCfg(CoreCfg coreCfg) {
        this.coreCfg = coreCfg;
    }
}
