/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Wait.java
 *
 * Created on 26-jun-2011, 18:20:31
 */

package org.iesapp.framework.pluggable;

import java.awt.Window;
import java.lang.reflect.Method;


/**
 *
 * @author Josep
 */
public class Loading extends javax.swing.JFrame {

    public boolean stop = false;

    /** Creates new form Wait */
    public Loading() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setAlwaysOnTop(true);
        this.getRootPane().setOpaque(false);
         try {
           Class<?> awtUtilitiesClass = Class.forName("com.sun.awt.AWTUtilities");
           Method mSetWindowOpacity = awtUtilitiesClass.getMethod("setWindowOpacity", Window.class, float.class);           
           mSetWindowOpacity.invoke(null, this, Float.valueOf(0.5f));
           
           
// Example of dynamic instances
           
//           Class<?> kk = Class.forName("org.iesapp.anuncis.AnunciEditor");
//           Constructor<?> constructor = kk.getConstructor(Frame.class, boolean.class);
//            try {
//                Object newInstance = constructor.newInstance(null,false);
//                javax.swing.JDialog win = (javax.swing.JDialog) newInstance;
//                win.setVisible(true);
//            } catch (InstantiationException ex) {
//                Logger.getLogger(AnuncisDlg.class.getName()).log(Level.SEVERE, null, ex);
//            }
           
          
           
        } catch (Exception ex) {
        }
    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/iesapp/framework/icons/loading.gif"))); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
