/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.iesapp.framework.pluggable;

import java.awt.Component;
import java.awt.Container;
import javax.swing.JScrollPane;

/**
 *
 * @author Josep
 */
public class StatusBarZone extends JScrollPane {

    /**
     * Creates new form StatusBarZonePanel
     */
    public StatusBarZone() {
        initComponents();
    }

     
    public void addComponent(Component comp)
    {
        jPanel1.add(comp);
        jPanel1.validate();
//        jPanel1.repaint();
    }

    public void clear()
    {
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.repaint();
    }
    
    /**
     * Remove all components with specified name and componentClass
     * @param name if null, remove all components of class type componentClass
      * @param componentClass if null, remove all components of given component name
      * if both null, it is an alias of clear
     */
    public void removeComponentsBy(String name, Class<?> componentClass) {
        if(name==null && componentClass==null)
        {
            this.clear();
            return;
        }
        else
        {
            removeWithin(jPanel1, name, componentClass);  //DO A RECURSIVE SEARCH
        }
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    private void removeWithin(Container holder, String name, Class<?> componentClass)
    {
            for(Component comp: holder.getComponents())
            {
                if( (name==null  || name.equals(comp.getName()) ) && 
                    (componentClass==null || componentClass.equals(comp.getClass()) ))
                {
                    jPanel1.remove(comp);
                }
                else if(comp instanceof Container)
                {
                    removeWithin((Container) comp, name, componentClass);
                }
            }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 3, 0);
        flowLayout1.setAlignOnBaseline(true);
        jPanel1.setLayout(flowLayout1);
        setViewportView(jPanel1);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
}
