/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UpdateAmon.java
 *
 * Created on 24-jun-2011, 17:54:50
 */

package org.iesapp.framework.admin;



import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Timer;
import org.iesapp.clients.iesdigital.dates.Avaluacions;
import org.iesapp.clients.iesdigital.fitxes.SGDImporter;
import org.iesapp.clients.iesdigital.fitxes.SGDImporterConfig;
import org.iesapp.database.MyDatabase;
import org.iesapp.framework.admin.cfg.SgdConfig;
import org.iesapp.framework.util.CoreCfg;
import org.iesapp.util.DataCtrl;
import org.iesapp.util.StringUtils;


/**
 *
 * @author Josep
 */
public class UpdateFromSGDdlg extends javar.JRDialog {
    private MyDatabase sgd;
    private SGDImporter task;
    private final int AnimationRate=1000;
    private final Timer timer;
    private final DefaultComboBoxModel modelCombo1;
    private final String invokeUser ;
    private final CoreCfg coreCfg;

    /** Creates new form UpdateAmon */
    public UpdateFromSGDdlg(java.awt.Frame parent, boolean modal, String invokeUser, CoreCfg coreCfg) {
        super(parent, modal);
        this.coreCfg = coreCfg;
        initComponents();
        this.invokeUser = invokeUser;

        sgd = new MyDatabase(CoreCfg.coreDB_sgdHost, CoreCfg.coreDB_sgdDB,
                CoreCfg.coreDB_sgdUser, CoreCfg.coreDB_sgdPasswd, CoreCfg.coreDB_sgdParam);
        boolean q = sgd.connect();
        if(!q)
        {
            SgdConfig dlg = new SgdConfig(parent, true, coreCfg);
            dlg.setLocationRelativeTo(null);
            dlg.setVisible(true);
            if(dlg.Ok)
            {
                 sgd = new MyDatabase(CoreCfg.coreDB_sgdHost, CoreCfg.coreDB_sgdDB,
                 CoreCfg.coreDB_sgdUser, CoreCfg.coreDB_sgdPasswd, CoreCfg.coreDB_sgdParam);
                 q = sgd.connect();
            }
            else
            {
                jButton1.setEnabled(false);
            }
        }

        modelCombo1 = new DefaultComboBoxModel();
      
        if(q)
        {
            String SQL1 = "SHOW DATABASES";
            try {
                Statement st = sgd.createStatement();
                ResultSet rs1 = sgd.getResultSet(SQL1,st); 
                while (rs1.next()) {
                    String txt = rs1.getString("Database");
                    if(txt.startsWith((String) CoreCfg.configTableMap.get("sgdDBPrefix")) && !txt.contains("tmp")){
                          modelCombo1.addElement(txt);
                    }
                }
                if(rs1!=null)
                {
                    rs1.close();
                    st.close();
                }
            } catch (SQLException ex) {
                Logger.getLogger(UpdateFromSGDdlg.class.getName()).log(Level.SEVERE, null, ex);
            }

 
            jComboBox1.setModel(modelCombo1);
            jComboBox1.setSelectedIndex(modelCombo1.getSize()-1);
          
            doConnect();
            setAvaluacions();
            setLlistesCodigs();
        }
        
        timer = new javax.swing.Timer(AnimationRate, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (task != null && task.isAlive()) {
                    jButton1.setEnabled(false);
                    jButton2.setEnabled(false);
                    jProgressBar1.setValue((int) task.getStatus());
                    jTextArea1.append(task.getLogoutput());
                } 
                else {
                    jButton1.setEnabled(true);
                    jButton2.setEnabled(true);
                    jTextArea1.setText("");
                    jTextArea1.append(task.getLogoutput());
                    timer.stop();
                    jProgressBar1.setValue(100);
                }
            }
        });


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Importa des de SGD");

        jButton1.setText("Import");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Close");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setText("SGD database");
        jLabel9.setName("jLabel9"); // NOI18N

        jProgressBar1.setName("jProgressBar1"); // NOI18N

        jComboBox1.setName("jComboBox1"); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel12.setText("to iesdigital for year");
        jLabel12.setName("jLabel12"); // NOI18N

        jSplitPane1.setResizeWeight(0.4);
        jSplitPane1.setName("jSplitPane1"); // NOI18N

        jPanel4.setName("jPanel4"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("List of defined simbols"));
        jPanel1.setName("jPanel1"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setToolTipText("Configurable des de l'script");
        jTextArea2.setName("jTextArea2"); // NOI18N
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Terms dates"));
        jPanel2.setName("jPanel2"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setToolTipText("Configurable des de l'administrador");
        jTextArea3.setName("jTextArea3"); // NOI18N
        jScrollPane3.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jSplitPane1.setLeftComponent(jPanel4);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Log"));
        jPanel3.setName("jPanel3"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jSplitPane1.setRightComponent(jPanel3);

        jTextField1.setEditable(false);
        jTextField1.setName("jTextField1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSplitPane1)
                .addGap(5, 5, 5)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(task!=null && task.isAlive()) {
            return;
        }
        sgd.close();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String sgdBase = (String) jComboBox1.getSelectedItem();

        String aux= StringUtils.AfterLast(sgdBase, (String) CoreCfg.configTableMap.get("sgdDBPrefix"));
        int any = Integer.parseInt(aux);
      
        sgd = new MyDatabase(CoreCfg.coreDB_sgdHost, sgdBase,
                CoreCfg.coreDB_sgdUser, CoreCfg.coreDB_sgdPasswd, CoreCfg.coreDB_sgdParam);
        boolean q = sgd.connect();

        timer.start();

        task = new SGDImporter(sgdBase, any+"", invokeUser, -1, null, coreCfg.getIesClient());
        task.start();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
        //si canviant la base d'origen
        //Canviarem tambe el curs destí
        
        int any = getSelectedAny();
      
        String desti=any+"-"+(any+1);
        jTextField1.setText(desti);
        
        doConnect();
        setAvaluacions();
        setLlistesCodigs();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void doConnect()
    {
          if(sgd!=null) {
            sgd.close();
          }
          String db = (String) jComboBox1.getSelectedItem();
          sgd = new MyDatabase(CoreCfg.coreDB_sgdHost,  db,
                 CoreCfg.coreDB_sgdUser, CoreCfg.coreDB_sgdPasswd, CoreCfg.coreDB_sgdParam);
                 boolean q = sgd.connect();
    }
 
    private void setLlistesCodigs()
    {
        jTextArea2.setText("");
        SGDImporterConfig updateSGDConfig = new SGDImporterConfig(this.getSelectedAny(), coreCfg.getIesClient());
        for(String ky: updateSGDConfig.getListSimbolsIds().keySet())
        {
            ArrayList<Integer> ids = updateSGDConfig.getListSimbolsIds().get(ky);
            String commentrequired = "";
            if(updateSGDConfig.getListCommentRequired().contains(ky)) {
                commentrequired = " (comment required)";    
            }
            
            jTextArea2.append("> identificador="+ky+commentrequired+" : importa ids="+ids.toString()+"\n");
        }
        jTextArea2.setCaretPosition(0);
    }


    private void setAvaluacions()
    {
        jTextArea3.setText("");
        ArrayList<Avaluacions> allAvaluacions = Avaluacions.getAllAvaluacions(getSelectedAny(), coreCfg.getIesClient());
        for(Avaluacions aval: allAvaluacions)
        {
           
           jTextArea3.append("[AMBITS]-->  " + aval.getEnsenyament()+" | "+aval.getEstudis()+"\n");
       
           jTextArea3.append("1a aval: de "+ new DataCtrl(aval.getFechaInicios().get("1")).getDiaMesComplet() +"  a  "+ new DataCtrl(aval.getFechaFins().get("1")).getDiaMesComplet()+"\n");
           jTextArea3.append("2a aval: de "+ new DataCtrl(aval.getFechaInicios().get("2")).getDiaMesComplet() +"  a  "+ new DataCtrl(aval.getFechaFins().get("2")).getDiaMesComplet()+"\n");
           jTextArea3.append("3a aval: de "+ new DataCtrl(aval.getFechaInicios().get("3")).getDiaMesComplet() +"  a  "+ new DataCtrl(aval.getFechaFins().get("3")).getDiaMesComplet()+"\n\n");
        }
        jTextArea3.setCaretPosition(0);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private ArrayList<Number> listAL;
    private ArrayList<Number> listAG;
    private ArrayList<Number> listAH;
    private ArrayList<Number> listFJ;
    private ArrayList<Number> listFA;
    private ArrayList<Number> listRE;

    private int getSelectedAny() {
        int any = 0;
        String orig = (String) jComboBox1.getSelectedItem();
        String aux= StringUtils.AfterLast(orig, (String) CoreCfg.configTableMap.get("sgdDBPrefix"));
        any = Integer.parseInt(aux);
        return any;    
    }

}


