/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.iesapp.framework.start;

import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionListener;
import org.iesapp.framework.util.CoreCfg;

/**
 *
 * @author Josep
 */
public final class StartupStep2 extends javax.swing.JPanel {
    private final DefaultListModel listmodel1;
    private final CoreCfg tmpClient;

    /**
     * Creates new form StartupStep2
     */
    public StartupStep2() {
        initComponents();
        tmpClient = StartupWiz.getTmpClient();
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
        updateComponents();    
        listmodel1 = new DefaultListModel();

    }

    public void loadDBsInHost()
    {
        
        String SQL = "Show databases";
        if(tmpClient.getMysql().isClosed())
        {
            System.out.println("ERROR: connection is lost");
            return;
        }
        
        try {
            Statement st = tmpClient.getMysql().createStatement();
            ResultSet rs1 = tmpClient.getMysql().getResultSet(SQL,st);
            while(rs1!=null && rs1.next())
            {
                listmodel1.addElement(rs1.getString(1));
            }
            if(rs1!=null) {
                rs1.close();
                st.close();
            }
        } catch (SQLException ex) {
            Logger.getLogger(StartupStep2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jList1.setModel(listmodel1);
        
        if( CoreCfg.core_mysqlDBPrefix.isEmpty()) 
        {
            jTextField2.setText("");
        }
        else
        {
            jTextField2.setText(CoreCfg.core_mysqlDBPrefix);
            jRadioButton1.setSelected(true);
            jList1.setSelectedValue(CoreCfg.core_mysqlDBPrefix, true);
        }
        int indexOf = listmodel1.indexOf("iesdigital_demo");
        if(StartupWiz.configType==StartupStep0.PORTABLE_MYSQL && indexOf>=0)
        {
            jRadioButton1.setSelected(true);
            jList1.setSelectedIndex(indexOf);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    public void registerActionButton1(ActionListener listener)
    {
        jRadioButton1.addActionListener(listener);
        jRadioButton2.addActionListener(listener);
    }
    
    public void registerKeyListener(KeyListener listener)
    {
        jTextField2.addKeyListener(listener);
    }
    
    public void registerActionList1(ListSelectionListener listener)
    {
        jList1.addListSelectionListener(listener);
    }
    
    public boolean isValidDatabase()
    {
        boolean q = false;
        if(jRadioButton2.isSelected())
        {
            if(!jTextField2.getText().trim().isEmpty()) 
            {
                String txt =  jTextField2.getText().trim().replaceAll(" ", "_");
                if(tmpClient.getMysql().setCatalog(txt)==1)
                {
                    q = false;
                   //Error this database already exits
                    JOptionPane.showMessageDialog(javar.JRDialog.getActiveFrame(), "Aquesta base de dades ja existeix. Trieu un altre nom");
                }
                else
                {
                    q = true;
                }
            }
        }
        else
        {
            if(jList1.getSelectedIndex()>=0) {
                q=true;
            }
        }
        return q;
    }
    
    public boolean saveToFile()
    {
        boolean q = true;
        
        if(jRadioButton2.isSelected())
        {
            CoreCfg.core_mysqlDBPrefix =  jTextField2.getText().trim().replaceAll(" ", "_");
            if(tmpClient.getMysql().setCatalog(CoreCfg.core_mysqlDBPrefix)==1)
            {
                q = false;
                //Error this database already exits
                JOptionPane.showMessageDialog(javar.JRDialog.getActiveFrame(), "Aquesta base de dades ja existeix. Trieu un altre nom");
            }
        }
        else
        {
            CoreCfg.core_mysqlDBPrefix =  (String) jList1.getSelectedValue();
        }        
        
        if(q) 
        {
            //Saves the encrypted file
            CoreCfg.saveEncryptedFile();
            //Create a blank database 
            if(jRadioButton2.isSelected()) {
                tmpClient.createEmptyDB(CoreCfg.core_mysqlDBPrefix);
            }
        }
        
        return q;
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        jRadioButton1.setText("Base existent");

        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Crear una base nova en blanc");

        jLabel3.setText("Bases de dades en el host (no inclogueu l'any)");

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 48, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Prefix de la base (no inclogueu l'any)");

        jTextField2.setText("iesdigital");
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextField2))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2KeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    public void updateComponents() {
        if(jRadioButton2.isSelected())
        {
            jList1.setEnabled(false);
            jTextField2.setEnabled(true);
        }
        else
        {
            jList1.setEnabled(true);
            jTextField2.setEnabled(false);
        }
    }
}
